from main import handle_inputs, fmi_method


list_of_inputs = [{
    "user": "adult",
    "place": "center",
    "long": "-122.416191",
    "lat": "37.786860",
    "walking_time": "15",
    "amenity1": "kindergarten",
    "amenity2": "restaurant",
    "amenity3": "bank",
    "avb-pref": "right",
    "avb": "3",
    "avc-pref": "right",
    "avc": "3",
    "bvc-pref": "left",
    "bvc": "1",
    "pavb-pref": "left",
    "pavb": "7",
    "pavc-pref": "left",
    "pavc": "5",
    "pbvc-pref": "right",
    "pbvc": "3",
 },
{
        "user": "adult",
        "place": "suburb",
        "long": "-122.462732",
        "lat": "37.747371",
        "walking_time": "15",
        "amenity1": "kindergarten",
        "amenity2": "restaurant",
        "amenity3": "bank",
        "avb-pref": "right",
        "avb": "3",
        "avc-pref": "right",
        "avc": "3",
        "bvc-pref": "left",
        "bvc": "1",
        "pavb-pref": "left",
        "pavb": "7",
        "pavc-pref": "left",
        "pavc": "5",
        "pbvc-pref": "right",
        "pbvc": "3",
},
{
        "user": "adult",
        "place": "uni",
        "long": "-122.457733",
        "lat": "37.774480",
        "walking_time": "15",
        "amenity1": "kindergarten",
        "amenity2": "restaurant",
        "amenity3": "bank",
        "avb-pref": "right",
        "avb": "3",
        "avc-pref": "right",
        "avc": "3",
        "bvc-pref": "left",
        "bvc": "1",
        "pavb-pref": "left",
        "pavb": "7",
        "pavc-pref": "left",
        "pavc": "5",
        "pbvc-pref": "right",
        "pbvc": "3",
},
    {
        "user": "grandma",
        "place": "center",
        "long": "-122.416191",
        "lat": "37.786860",
        "walking_time": "15",
        "amenity1": "hospital",
        "amenity2": "church",
        "amenity3": "supermarket",
        "avb-pref": "right",
        "avb": "3",
        "avc-pref": "right",
        "avc": "4",
        "bvc-pref": "right",
        "bvc": "2",
        "pavb-pref": "left",
        "pavb": "5",
        "pavc-pref": "left",
        "pavc": "3",
        "pbvc-pref": "right",
        "pbvc": "2",
},
    {
        "user": "grandma",
        "place": "suburb",
        "long": "-122.462732",
        "lat": "37.747371",
        "walking_time": "15",
        "amenity1": "hospital",
        "amenity2": "church",
        "amenity3": "supermarket",
        "avb-pref": "right",
        "avb": "3",
        "avc-pref": "right",
        "avc": "4",
        "bvc-pref": "right",
        "bvc": "2",
        "pavb-pref": "left",
        "pavb": "5",
        "pavc-pref": "left",
        "pavc": "3",
        "pbvc-pref": "right",
        "pbvc": "2",
},
    {
        "user": "grandma",
        "place": "uni",
        "long": "-122.457733",
        "lat": "37.774480",
        "walking_time": "15",
        "amenity1": "hospital",
        "amenity2": "church",
        "amenity3": "supermarket",
        "avb-pref": "right",
        "avb": "3",
        "avc-pref": "right",
        "avc": "4",
        "bvc-pref": "right",
        "bvc": "2",
        "pavb-pref": "left",
        "pavb": "5",
        "pavc-pref": "left",
        "pavc": "3",
        "pbvc-pref": "right",
        "pbvc": "2",
},
    {
        "user": "student",
        "place": "center",
        "long": "-122.416191",
        "lat": "37.786860",
        "walking_time": "15",
        "amenity1": "university",
        "amenity2": "bar",
        "amenity3": "cafe",
        "avb-pref": "left",
        "avb": "3",
        "avc-pref": "left",
        "avc": "2",
        "bvc-pref": "right",
        "bvc": "3",
        "pavb-pref": "left",
        "pavb": "4",
        "pavc-pref": "left",
        "pavc": "6",
        "pbvc-pref": "left",
        "pbvc": "3",
},
    {
        "user": "student",
        "place": "suburb",
        "long": "-122.462732",
        "lat": "37.747371",
        "walking_time": "15",
        "amenity1": "university",
        "amenity2": "bar",
        "amenity3": "cafe",
        "avb-pref": "left",
        "avb": "3",
        "avc-pref": "left",
        "avc": "2",
        "bvc-pref": "right",
        "bvc": "3",
        "pavb-pref": "left",
        "pavb": "4",
        "pavc-pref": "left",
        "pavc": "6",
        "pbvc-pref": "left",
        "pbvc": "3",
},
    {
        "user": "student",
        "place": "uni",
        "long": "-122.457733",
        "lat": "37.774480",
        "walking_time": "15",
        "amenity1": "university",
        "amenity2": "bar",
        "amenity3": "cafe",
        "avb-pref": "left",
        "avb": "3",
        "avc-pref": "left",
        "avc": "2",
        "bvc-pref": "right",
        "bvc": "3",
        "pavb-pref": "left",
        "pavb": "4",
        "pavc-pref": "left",
        "pavc": "6",
        "pbvc-pref": "left",
        "pbvc": "3",
},
]

examples_results = []
for inputs in list_of_inputs:
    handled_inputs = handle_inputs(inputs)
    result = fmi_method(handled_inputs)
    example_result = {f"{inputs['user']}_{inputs['place']}": result}
    examples_results.append(result)

print(examples_results)
